include $(THEOS)/makefiles/common.mk

TOOL_NAME = hidsupporttest
hidsupporttest_FILES = main.c
hidsupporttest_CFLAGS = -I..
hidsupporttest_LIBRARIES += hidsupport
hidsupporttest_LDFLAGS = -L../.theos/obj/debug

include $(THEOS_MAKE_PATH)/tool.mk
