include $(THEOS)/makefiles/common.mk


ARCHS = arm64

TOOL_NAME = hidsample

hidsample_FILES = main.mm
hidsample_CFLAGS= -I..
hidsample_LDFLAGS=-L../.theos/obj/debug -lhidsupport


include $(THEOS_MAKE_PATH)/tool.mk
